// Sample product data with categories
const products = [
    // Floral (Totebag Lukisan Asli) - 10 items
    {
        id: 1,
        name: "Suasana Candi Prambanan",
        description: "Totebag lukisan asli bertema Suasana Candi Prambanan yang merepresentasikan ikon budaya Jawa. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/1.png", "image/totebag/asli/2.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "sakura", "romantic"]
    },
    {
        id: 2,
        name: "Kreaton Solo",
        description: "Totebag lukisan asli bertema Kraton Solo yang merepresentasikan ikon budaya dan sejarah Jawa. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/2.png", "image/totebag/asli/3.PNG"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "rose", "passion"]
    },
    {
        id: 3,
        name: "Suasana Kali Code",
        description: "Totebag lukisan asli bertema Suasana Kali Code yang menampilkan keindahan flora dalam karya seni. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/3.PNG", "image/totebag/asli/4.PNG"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "tulip", "cheerful"]
    },
    {
        id: 4,
        name: "Makam Raja Mataram",
        description: "Totebag lukisan asli bertema Makam Raja Mataram yang merepresentasikan nilai sejarah dan budaya Jawa. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/4.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "lavender", "calming"]
    },
    {
        id: 5,
        name: "Pasar Beringharjo",
        description: "Totebag lukisan asli bertema Pasar Beringharjo yang merepresentasikan aktivitas dan budaya khas Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/5.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "sunflower", "joyful"]
    },
    {
        id: 6,
        name: "Pasar Kota Gede",
        description: "Totebag lukisan asli bertema Pasar Kota Gede yang merepresentasikan suasana dan aktivitas pasar tradisional. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/6.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "orchid", "elegant"]
    },
    {
        id: 7,
        name: "Gereja Gothic Sayidan",
        description: "Totebag lukisan asli bertema Gereja Gothic Sayidan yang merepresentasikan ikon arsitektur dan sejarah kawasan Sayidan. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/7.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "daisy", "fresh"]
    },
    {
        id: 8,
        name: "Suasana Candi Prambanan",
        description: "Totebag lukisan asli bertema Suasana Candi Prambanan yang merepresentasikan keindahan dan nilai sejarah budaya Jawa. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/8.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "peony", "prosperity"]
    },
    {
        id: 9,
        name: "Suasana Kali Code",
        description: "Totebag lukisan asli bertema Suasana Kali Code yang merepresentasikan kehidupan dan lingkungan khas Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/9.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "lily", "graceful"]
    },
    {
        id: 10,
        name: "Chinatown Malioboro",
        description: "Totebag lukisan asli bertema Chinatown Malioboro yang merepresentasikan kawasan budaya dan aktivitas khas Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 500000,
        originalPrice: 600000,
        category: "lukisan-asli",
        images: ["image/totebag/asli/10.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "42cm x 35cm",
            "Teknik": "Lukisan tangan dengan cat akrilik",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["floral", "wildflowers", "adventure"]
    },

    // Print (Totebag Print) - 10 items
    {
        id: 11,
        name: "Bahasa Kami",
        description: "Totebag printing bertema Bahasa Kami yang merepresentasikan ekspresi bahasa isyarat. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/bahasa kami/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["best-seller", "floral", "elegant"]
    },
    {
        id: 12,
        name: "Gadis Tuli",
        description: "Totebag printing bertema Gadis Tuli yang menampilkan ekspresi diri dan karakter perempuan Tuli. Cocok untuk penggunaan harian.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/gadis tuli/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["abstract", "modern", "artistic"]
    },
    {
        id: 13,
        name: "Gapura Pecinan Yogyakarta",
        description: "Totebag printing bertema Gapura Pecinan Yogyakarta yang merepresentasikan ikon budaya dan sejarah kota. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/Gapura Pecinan Yogyakarta/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["minimalist", "black-white", "sophisticated"]
    },
    {
        id: 14,
        name: "Kali Code",
        description: "Totebag printing bertema Kali Code yang merepresentasikan kehidupan dan lanskap khas Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/Kali Code/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["vintage", "landscape", "limited-edition"]
    },
    {
        id: 15,
        name: "Makam Raja Mataram",
        description: "Totebag printing bertema Makam Raja Mataram yang merepresentasikan nilai sejarah dan budaya Jawa. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/Makam Raja Mataram/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["ocean", "blue", "calming"]
    },
    {
        id: 16,
        name: "Jalan Maliaboro",
        description: "Totebag printing bertema Jalan Malioboro yang merepresentasikan suasana ikonik pusat kota Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/Maliaboro 1/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["ilustrasi", "kucing", "cute"]
    },
    {
        id: 17,
        name: "Jalan Maliaboro",
        description: "Totebag printing bertema Jalan Malioboro yang merepresentasikan suasana ikonik pusat kota Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/maliaboro 2/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["bahasa", "budaya", "indonesia"]
    },
    {
        id: 18,
        name: "Pinggiran Maliaboro",
        description: "Totebag printing bertema Pinggiran Malioboro yang merepresentasikan sudut khas Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/pinggiran maliaboro/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["malioboro", "yogyakarta", "iconic"]
    },
    {
        id: 19,
        name: "Tugu Pal Putih",
        description: "Totebag printing bertema Tugu Pal Putih yang merepresentasikan ikon dan identitas Kota Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/tugu pal putih/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["borobudur", "temple", "cultural"]
    },
    {
        id: 20,
        name: "Tugu Pal Putih",
        description: "Totebag printing bertema Tugu Pal Putih yang merepresentasikan ikon dan identitas Kota Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 250000,
        originalPrice: 300000,
        category: "print",
        images: ["image/totebag/print/Tugu Pal Putih 1/4.png"],
        features: {
            "Bahan": "Kanvas Blacu Berkualitas",
            "Ukuran": "35cm x 42cm",
            "Teknik": "Printing",
            "Tali": "Jahit kuat",
            "Warna Dasar": "Warna",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["tugu", "yogyakarta", "landmark"]
    },

    // Pouch - 3 items
    {
        id: 21,
        name: "Wisata Yogyakarta",
        description: "Pouch lukisan bertema Wisata Yogyakarta yang merepresentasikan ikon dan ragam destinasi kota Yogyakarta. Cocok digunakan untuk menyimpan barang kecil sehari-hari.",
        price: 100000,
        originalPrice: 120000,
        category: "pouch",
        images: ["image/pouch/5.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "A5",
            "Teknik": "Lukisan tangan oleh seniman Tuli",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Putih / Hitam",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["pouch-lukis", "wisata-yogyakarta", "karya-tuli"]
    },
    {
        id: 22,
        name: "Wisata Yogyakarta",
        description: "Pouch lukisan bertema Wisata Yogyakarta yang merepresentasikan ikon dan ragam destinasi kota Yogyakarta. Cocok digunakan untuk menyimpan barang kecil sehari-hari.",
        price: 100000,
        originalPrice: 120000,
        category: "pouch",
        images: ["image/pouch/5.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "A5",
            "Teknik": "Lukisan tangan oleh seniman Tuli",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Putih / Hitam",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["pouch-lukis", "wisata-yogyakarta", "karya-tuli"]
    },
    {
        id: 23,
        name: "Wisata Yogyakarta",
        description: "Pouch lukisan bertema Wisata Yogyakarta yang merepresentasikan ikon dan ragam destinasi kota Yogyakarta. Cocok digunakan untuk menyimpan barang kecil sehari-hari.",
        price: 100000,
        originalPrice: 120000,
        category: "pouch",
        images: ["image/pouch/5.png"],
        features: {
            "Bahan": "Kanvas Bandung",
            "Ukuran": "A5",
            "Teknik": "Lukisan tangan oleh seniman Tuli",
            "Finishing": "Dilapisi pilox clear",
            "Warna Dasar": "Putih / Hitam",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["pouch-lukis", "wisata-yogyakarta", "karya-tuli"]
    },

    // Masker - 4 items
    {
        id: 24,
        name: "Masker Ilustrasi Abstrak",
        description: "Masker kain bertema ilustrasi abstrak yang dicetak dari karya seni sebagai bagian dari produk kreatif Bariz. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 45000,
        originalPrice: 55000,
        category: "masker",
        images: ["image/masker/masker ilustrasi/abstrak/1.png"],
        features: {
            "Bahan": "Katun 3 lapis",
            "Ukuran": "17cm x 10cm",
            "Teknik": "Printing dari karya ilustrasi",
            "Tali": "Karet elastis",
            "Warna Dasar": "Putih / Sesuai desain",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["masker", "ilustrasi", "karya-tuli"]
    },
    {
        id: 25,
        name: "Masker Bahasa Kami",
        description: "Masker kain bertema Bahasa Kami yang merepresentasikan ekspresi bahasa isyarat sebagai identitas komunitas Tuli. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 42000,
        originalPrice: 52000,
        category: "masker",
        images: ["image/masker/masker print/Bahasa Kami/2.png"],
        features: {
            "Bahan": "Katun 3 lapis",
            "Ukuran": "17cm x 10cm",
            "Teknik": "Printing dari karya ilustrasi",
            "Tali": "Karet elastis",
            "Warna Dasar": "Putih / Sesuai desain",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["masker", "bahasa-isyarat", "karya-tuli"]
    },
    {
        id: 26,
        name: "Masker Makam Raja Mataram",
        description: "Masker kain bertema Makam Raja Mataram yang merepresentasikan nilai sejarah dan budaya Jawa. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 38000,
        originalPrice: 48000,
        category: "masker",
        images: ["image/masker/masker print/Makam Raja Mataram Kota Gede/3.png"],
        features: {
            "Bahan": "Katun 3 lapis",
            "Ukuran": "17cm x 10cm",
            "Teknik": "Printing dari karya ilustrasi",
            "Tali": "Karet elastis",
            "Warna Dasar": "Putih / Sesuai desain",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["masker", "budaya", "karya-tuli"]
    },
    {
        id: 27,
        name: "Masker Taman Sari",
        description: "Masker kain bertema Taman Sari yang merepresentasikan ikon sejarah dan budaya Yogyakarta. Cocok digunakan untuk aktivitas sehari-hari.",
        price: 48000,
        originalPrice: 58000,
        category: "masker",
        images: ["image/masker/masker Print/Taman Sari/4.png"],
        features: {
            "Bahan": "Katun 3 lapis",
            "Ukuran": "17cm x 10cm",
            "Teknik": "Printing dari karya ilustrasi",
            "Tali": "Karet elastis",
            "Warna Dasar": "Putih / Sesuai desain",
            "Perawatan": "Disarankan cuci manual"
        },
        inStock: true,
        tags: ["masker", "taman-sari", "karya-tuli"]
    },

    // Lukisan Asli (Karya Lukisan) - 1 item
    {
        id: 28,
        name: "Hotel Tugu Series",
        description: "Karya ini mengeksplorasi arsitektur monumental Hotel Tugu sebagai saksi hidup yang berdialog dengan denyut kehidupan urban kontemporer. Melalui lapisan cat transparan yang mempertahankan ingatan visual, lukisan ini merangkai metafora mendalam tentang stratifikasi sejarah sebuah kota.",
        price: 5500000,
        originalPrice: 6000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/1.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 29,
        name: "Candi Prambanan Series",
        description: "Karya ini mengeksplorasi dialektika antara monumentalitas arsitektur Candi Prambanan dan pusaran energi spiritual yang terus beresonansi di dalamnya. Struktur geometris yang kokoh berdialog dengan medan cahaya dinamis, menghadirkan ketegangan indah antara permanensi bentuk dan fluiditas spiritual.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/2.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 30,
        name: "Klenteng di Pusat Kota",
        description: "Karya ini mengeksplorasi klenteng sebagai mozaik budaya Yogyakarta, memadukan teknik opaque pada arsitektur dan aquarel transparan untuk cahaya lampion. Ruang sakral ini menciptakan dialog harmonis antara keteguhan iman masa lampau dan ritme kehidupan urban kontemporer.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/3.png"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 31,
        name: "Kantor Pos Yogyakarta",
        description: "Karya ini mengeksplorasi Kantor Pos Yogyakarta sebagai jejak arsitektur kolonial yang bertransformasi menjadi ruang publik interaktif. Perpaduan teknik opaque dan aquarel menciptakan dialog visual antara kokohnya struktur masa lalu dan dinamika masyarakat kontemporer.",
        price: 5500000,
        originalPrice: 6000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/4.png"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 32,
        name: "Keraton Solo",
        description: "Karya ini mengeksplorasi keagungan Keraton Solo sebagai episentrum kebudayaan Jawa melalui perpaduan teknik opaque dan aquarel yang harmonis. Kanvas ini merekam istana bukan sekadar bangunan fisik, melainkan jantung spiritual yang terus berdetak melintasi pusaran zaman.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/5.png"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 33,
        name: "Pradaksina Jalan Cahaya",
        description: "Karya ini memvisualisasikan hormat pada ritual sakral Candi Borobudur. Garis abu-abu merekam harmoni langkah manusia dengan rotasi kosmos di bawah langit malam yang magis, menciptakan meditasi visual tentang keselarasan alam semesta",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/6.jpeg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 34,
        name: "Candi Plaosan",
        description: "Karya ini memvisualisasikan kemegahan Candi Plaosan melalui dominasi warna merah dan jingga yang membara. Sentuhan biru, hijau, dan kuning neon pada pepohonan menghadirkan nuansa magis, sementara figur manusia di depan candi mempertegas harmoni kehidupan dan keabadian arsitektur.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/7.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 35,
        name: "Candi Prambanan",
        description: "Karya ini mengeksplorasi Candi Prambanan sebagai simbol spiritual dan warisan budaya yang hidup. Dominasi warna kuning dan hijau menghadirkan energi pagi yang hangat, sementara figur manusia dan alam membangun harmoni visual antara tradisi, kehidupan, dan kemegahan arsitektur candi.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/8.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 36,
        name: "Makam Raja-Raja Imogiri",
        description: "Karya ini merepresentasikan suasana sakral Makam Raja-Raja Imogiri melalui gapura dan tangga peziarahan yang penuh tekstur ekspresif. Dominasi langit merah muda dengan matahari merah dramatis berpadu dengan hijau tumbuhan di sekitarnya, menciptakan harmoni visual antara spiritualitas, perjalanan, dan ketenangan alam.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/9.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 37,
        name: "Candi Ratu Boko",
        description: "Karya ini mengeksplorasi kemegahan Situs Ratu Boko dalam balutan suasana malam yang hening dan misterius. Dominasi warna biru tua dan hijau toska berpadu dengan cahaya rembulan, sementara figur manusia dan sentuhan pink pada tanaman menghadirkan harmoni antara ketenangan, sejarah, dan kehidupan.",
        price: 6500000,
        originalPrice: 7000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/10.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 50cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2026",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 38,
        name: "Kehidupan Kota di Malam Hari",
        description: "Karya ini mengeksplorasi kepadatan urban dan ritme visual kota yang tak pernah tidur melalui sapuan gestur ekspresif yang intens. Denyut nadi kehidupan malam direkam dalam lapisan warna berani, memancarkan energi kolektif dari sebuah harmoni pergerakan konstan.",
        price: 7500000,
        originalPrice: 8000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/11.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "60cm x 80cm",
            "Teknik": "Opaque",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 39,
        name: "Metabolisme Perkotaan",
        description: "Karya ini memetakan sirkulasi jaringan urban untuk memvisualisasikan hiruk-pikuk kota layaknya sebuah organisme hidup yang terus bernapas dan beregenerasi. Kontras antara arsitektur kolonial dan denyut pembangunan kontemporer merepresentasikan ekologi perkotaan tempat segala sesuatu senantiasa runtuh dan bertumbuh.",
        price: 21000000,
        originalPrice: 21500000,
        category: "lukisan",
        images: ["image/karya lukisan asli/12.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "140cm x 85cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 40,
        name: "Antara Dua Gerbang",
        description: "Karya ini menyajikan rekonstruksi visual dramatis tentang konfrontasi sejarah antara kedaulatan tradisional dan kekuatan kolonial yang berbenturan keras. Melalui komposisi tegas dan elemen anakronistik, lukisan ini merangkai narasi waktu berlapis tentang kegigihan perlawanan yang melampaui sejarah spesifik.",
        price: 21000000,
        originalPrice: 21500000,
        category: "lukisan",
        images: ["image/karya lukisan asli/13.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "140cm x 85cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 41,
        name: "Navigasi Kolektif",
        description: "Karya ini menghadirkan metafora visual memukau tentang perjalanan kolektif yang berani menembus batas-batas keragaman budaya Nusantara. Berbagai figur tradisional dan kontemporer bersatu dalam perahu simbolis, menggemakan narasi harmoni serta solidaritas sebagai kekuatan abadi dalam menghadapi dinamika zaman.",
        price: 21000000,
        originalPrice: 21500000,
        category: "lukisan",
        images: ["image/karya lukisan asli/14.png"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "140cm x 85cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 42,
        name: "Dualitas Etika",
        description: "Karya ini mengeksplorasi dikotomi etika melalui representasi dua kekuatan mitologis berlawanan yang berbenturan dalam sebuah ketegangan dinamis. Figur simbolik kebajikan dan kegelapan menyatu untuk menciptakan metafora visual yang mendalam tentang konflik batin yang terus bergema dalam jiwa manusia.",
        price: 11500000,
        originalPrice: 12000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/15.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "60cm x 80cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 43,
        name: "Memori Kultural",
        description: "Karya ini mengeksplorasi kedalaman memori kultural melalui sosok feminin elegan yang berdialog dengan keanggunan arsitektur historis. Sapuan garis ekspresif dan perpaduan media yang dinamis menciptakan narasi rekonstruksi visual yang menghidupkan kembali identitas masa lalu sebagai pijakan kultural kini.",
        price: 10500000,
        originalPrice: 11000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/16.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "60cm x 80cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 44,
        name: "Pulsa Pasar Tradisional",
        description: "Karya ini merekam denyut pasar tradisional sebagai ekosistem kehidupan kolektif yang tak henti digerakkan oleh dinamika interaksi sosial dan ekonomi rakyat. Melalui komposisi padat dan garis ekspresif, kanvas ini mengabadikan kehangatan humanisme dan keaslian denyut budaya lokal.",
        price: 8000000,
        originalPrice: 8500000,
        category: "lukisan",
        images: ["image/karya lukisan asli/17.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "50cm x 80cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 45,
        name: "Cagar Budaya",
        description: "Karya ini merenungkan hubungan simbiosis harmonis antara warisan arsitektural purba dan kedamaian kehidupan agraris yang mengitarinya. Pemukiman di kaki candi digambarkan sebagai ruang hidup yang bernaung secara spiritual, menciptakan narasi abadi tentang kontinuitas budaya masa lalu dan kini.",
        price: 15500000,
        originalPrice: 16000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/18.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "70cm x 100cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 46,
        name: "Fantasi Jamur",
        description: "Karya ini menyajikan eksplorasi imajinatif tentang ekosistem jamur fantastis yang mempesona, dihuni oleh berbagai entitas magis yang tersembunyi. Melalui detail alam yang imersif, lukisan ini merangkai dunia alternatif yang menawarkan penyegaran tematik jauh dari kebisingan narasi urban.",
        price: 21000000,
        originalPrice: 21500000,
        category: "lukisan",
        images: ["image/karya lukisan asli/19.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "100cm x 130cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 47,
        name: "Pemandangan Agraria",
        description: "Karya ini mengeksplorasi lanskap agraris dan arsitektur vernakular dengan palet monokromatik atmosferik yang memancarkan ketenangan mendalam. Tarian sawah yang meliuk dan pegunungan pelindung merajut harmoni visual sempurna yang merepresentasikan kedamaian hidup pedesaan yang sejati.",
        price: 3500000,
        originalPrice: 4000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/20.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "50cm x 60cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 48,
        name: "Lanskap Budaya",
        description: "Karya ini merangkai sintesis visual agung yang menyatukan arsitektur monumental, bentang lanskap agraris, dan kehangatan hunian vernakular. Menempatkan struktur bersejarah sebagai penjaga kehidupan kontemporer, lukisan ini menuturkan sebuah epos visual abadi tentang kesinambungan warisan budaya lintas zaman.",
        price: 3500000,
        originalPrice: 4000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/21.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "50cm x 60cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 49,
        name: "Permadani Iman",
        description: "Karya ini menelusuri keberagaman religius Nusantara melalui pendekatan kolase kanvas yang kaya akan tekstur inovatif dan berlapis. Potongan material yang membentuk harmoni mozaik tempat ibadah melahirkan metafora visual bertenaga tentang indahnya kesatuan jiwa di tengah lautan perbedaan.",
        price: 10500000,
        originalPrice: 11000000,
        category: "lukisan",
        images: ["image/karya lukisan asli/22.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "65cm x 86cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 50,
        name: "BISINDO di Rumah",
        description: "Karya ini mengarahkan lensa naratif ke ranah privat untuk merepresentasikan bagaimana identitas bahasa isyarat dibentuk dan dirawat di dalam kehangatan keluarga. Sentuhan personal ini menandai perkembangan batin sang seniman, bergerak dari advokasi publik menuju kedekatan interpersonal.",
        price: 21000000,
        originalPrice: 21500000,
        category: "lukisan",
        images: ["image/karya lukisan asli/23.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "100cm x 100cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    {
        id: 51,
        name: "Ambang Batas Kota",
        description: "Karya ini memaknai gerbang kota sebagai titik pertemuan dinamis antara warisan arsitektur tradisional dan ritme kehidupan kontemporer. Ambang batas ini ditangkap melalui lapisan tekstur padat, menghadirkan esensi transisi urban sebagai ekosistem hidup yang terus berevolusi.",
        price: "Sold",
        originalPrice: "Sold",
        category: "lukisan",
        images: ["image/karya lukisan asli/24.jpg"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas",
            "Ukuran": "40cm x 40cm",
            "Teknik": "Opaque & Aquarel",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: false,
        tags: ["lukisan", "karya-tuli", "orisinal"]
    },
    // Payung Lukisan
    {
        id: 52,
        name: "Suasana Candi Prambanan",
        description: "Karya ini mengeksplorasi monumentalitas Candi Prambanan sebagai saksi peradaban kuno yang berdialog dengan energi spiritual abadi. Melalui lapisan cat akrilik transparan pada kanvas payung, merangkai harmoni antara arsitektur purba dan kehidupan kontemporer, menghadirkan pelindung budaya melampaui fungsi fisik.",
        price: 1500000,
        originalPrice: 2000000,
        category: "payung",
        images: ["image/payung/1.JPG"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas payung",
            "Ukuran": "40cm diameter",
            "Teknik": "Akrilik",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["payung", "karya-tuli", "orisinal", "candi-prambanan"]
    },
    {
        id: 53,
        name: "Suasana Tugu Pal Yogyakarta",
        description: "Karya ini mengeksplorasi Tugu Pal Yogyakarta sebagai ikon urban yang menghubungkan stratifikasi sejarah dengan dinamika kota modern. Melalui tekstur padat cat akrilik, payung ini menangkap esensi transisi sebagai ekosistem hidup, melindungi pemakainya dari ritme perkotaan yang terus berubah.",
        price: 1500000,
        originalPrice: 2000000,
        category: "payung",
        images: ["image/payung/2.JPG"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas payung",
            "Ukuran": "40cm diameter",
            "Teknik": "Akrilik",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["payung", "karya-tuli", "orisinal", "candi-prambanan"]
    },
    {
        id: 54,
        name: "Suasana Keraton Yogyakarta",
        description: "Karya ini mengeksplorasi Keraton Yogyakarta sebagai jantung kebudayaan Jawa yang berdetak melintasi zaman. Melalui perpaduan warna dan bentuk pada medium payung, lukisan ini merangkai narasi keagungan tradisional yang beradaptasi dengan denyut kehidupan kontemporer.",
        price: 1500000,
        originalPrice: 2000000,
        category: "payung",
        images: ["image/payung/3.JPG"],
        features: {
            "Nama Seniman": "Bagaskara Maharastu P.I",
            "Media": "Campur media di atas kanvas payung",
            "Ukuran": "40cm diameter",
            "Teknik": "Akrilik",
            "Finishing": "Dilapisi Varnish",
            "Tahun": "2025",
        },
        inStock: true,
        tags: ["payung", "karya-tuli", "orisinal", "candi-prambanan"]
    }
];

